[package]
name = "image_gen"
version = "0.1.0"
authors = ["brundolf"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
image = "0.21.2"
crossbeam = "0.7.2"